version: "3.9"
name: "btp2-eth2"
services:
  goloop:
    extends:
      file: ./icon/docker-compose.base.yml
      service: goloop
    ports:
      - 9080:9080
  geth:
    extends:
      file: ./eth2/docker-compose.base.yml
      service: geth
    ports:
      - 8545:8545
  lodestar0:
    extends:
      file: ./eth2/docker-compose.base.yml
      service: lodestar0
    ports:
      - 9596:9596
  lodestar1:
    extends:
      file: ./eth2/docker-compose.base.yml
      service: lodestar1
    ports:
      - 9597:9596
